In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from joblib import dump, load
import numpy as np

# Charger le dataset iris
X, y = load_iris(return_X_y=True)

# Séparer les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Définir le prétraitement pour les colonnes numériques et catégorielles
model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=500))

# Entraîner le pipeline sur les données d'entraînement
model.fit(X_train, y_train)

# Exporter le pipeline entraîné en tant que fichier .pkl
model_path = 'model.pkl'
dump(model, model_path)

['model.pkl']

In [3]:
model = load(model_path)

In [4]:
model.score(X_test, y_test)

1.0

In [5]:
X_test[0]

array([6.1, 2.8, 4.7, 1.2])

In [6]:
model.predict(X_test[0].reshape(1, -1))

array([1])

In [7]:
model.predict(X_test[0:1])

array([1])

In [8]:
X_test[0:1]

array([[6.1, 2.8, 4.7, 1.2]])

In [9]:
def load_model(path: str = 'model.pkl'):
    model = load(path)
    return model

model = load_model()

model.score(X_test, y_test)

1.0

In [10]:
def prediction(model, data):
    predictions = model.predict(data)
    return predictions

prediction(model, X_test[0:1])

array([1])

In [11]:
load_iris().keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [12]:
load_iris().feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
X_test[:3]

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3]])

In [14]:
y_test[:3]

array([1, 0, 2])